from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('internship', views.internship, name='internship'),
    path('update_payment', views.update_payment, name='update_payment'),
    path('circulars', views.circulars, name='circulars'),
    path('signup', views.signup_ep, name='signup'),
    path('send_otp', views.send_otp, name='send_otp'),
    path('verify_otp', views.verify_otp, name='verify_otp'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('login', views.login_ep, name='login'),
    path('logout', views.logout_ep, name='logout'),
    path('profile', views.profile, name='profile'),
    path('get_user_info', views.get_user_info, name='get_user_info'),
    path('add_users', views.add_users, name='add_users'),
    path('get_applications', views.get_applications, name='get_applications'),
    path('get_application_status', views.get_application_status, name='get_application_status'),
    path('view_final_applications', views.view_final_applications, name='view_final_applications'),
    path('view_applications', views.view_applications, name='view_applications'),
    path('get_application/<int:id>', views.get_application, name='get_application'),
    path('update_application', views.update_application, name='update_application'),
    path('get_hostel/<int:id>', views.get_hostel, name='get_hostel'),
    path('get_hostels', views.get_hostels, name='get_hostels'),
    path('rooms/<str:id>', views.room, name='get_rooms'),
    path('allot_room', views.allot_room, name='allot_room'),
    path('send_email', views.send_email, name='send_email'),
    path('generate_pdf', views.generate_pdf, name='generate_pdf'),
    path('unallocate_room', views.unallocate_room, name='unallocate_room'),
    path('receive_from_sandbox', views.receive_from_sandbox, name='receive_from_sandbox'),  
    path('get_saved_mappings', views.get_saved_mappings, name='get_saved_mappings'),
    path('get_saved_mapping', views.get_saved_mapping, name='get_saved_mapping'),
    path('delete_saved_mapping/<str:name>', views.delete_saved_mapping, name='delete_saved_mapping'),
    path('create_saved_mapping', views.create_saved_mapping, name='create_saved_mapping'),
    path('apply_saved_mapping', views.apply_saved_mapping, name='apply_saved_mapping'),
    path('check_mapping_validity', views.check_mapping_validity, name='check_mapping_validity'),
    path('add_data', views.add_data, name='add_data'),
    path('test', views.sandbox, name='sandbox'),
    path('get_students', views.get_students, name='get_students'),
    path('get_student/<int:id>', views.get_student, name='get_student'),
    path('new_room', views.new_room, name='new_room'),
    path('swap_room', views.swap_room, name='swap_room'),
    path('new_batch', views.new_batch, name='new_batch')
]